TWEAK_NAME = Jikan

$(TWEAK_NAME)_FILES = $(TWEAK_NAME).x JikanPlatterView/JikanPlatterView.m TT100/TT100.m TT100/TT100Database.m
$(TWEAK_NAME)_FRAMEWORKS = UIKit Foundation IOKit
$(TWEAK_NAME)_LIBRARIES += sqlite3
$(TWEAK_NAME)_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
